@apiKey = $2ys6g542sb4fb6b42fb4db409df498fd41682b6df24b884f9852dthv143r4t52trfg4trs6gfcdg53g43g
@postId = 6812d4310a1c81932a5f5dc1

### Créer un article
POST http://localhost:3000/api/posts
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "title": "Mon premier article",
  "content": "Ceci est le contenu de l'article",
  "image": "https://example.com/image.jpg",
  "authorId": "66322e7cf8a39e0a4be342a9",
  "tags": ["tech", "mongo"],
  "status": "draft"
}

### Obtenir tous les articles
GET http://localhost:3000/api/posts
x-api-key: {{apiKey}}

### Obtenir un article par ID
GET http://localhost:3000/api/posts/{{postId}}
x-api-key: {{apiKey}}

### Mettre à jour un article
PUT http://localhost:3000/api/posts/{{postId}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "title": "Article mis à jour",
  "status": "published"
}

### Supprimer un article
DELETE http://localhost:3000/api/posts/{{postId}}
x-api-key: {{apiKey}}
