@apiKey = $2ys6g542sb4fb6b42fb4db409df498fd41682b6df24b884f9852dthv143r4t52trfg4trs6gfcdg53g43g
@collectionId = 6812d54894b968b803b01c5e

### Créer une collection
POST http://localhost:3000/api/collections
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "title": "Collection Moderne",
  "artistId": "66322e7cf8a39e0a4be342a9",
  "artworkCount": 5
}

### Obtenir toutes les collections
GET http://localhost:3000/api/collections
x-api-key: {{apiKey}}

### Obtenir une collection par ID
GET http://localhost:3000/api/collections/{{collectionId}}
x-api-key: {{apiKey}}

### Mettre à jour une collection
PUT http://localhost:3000/api/collections/{{collectionId}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "title": "Collection Mis à jour"
}

### Supprimer une collection
DELETE http://localhost:3000/api/collections/{{collectionId}}
x-api-key: {{apiKey}}
