@apiKey = $2ys6g542sb4fb6b42fb4db409df498fd41682b6df24b884f9852dthv143r4t52trfg4trs6gfcdg53g43g
@reviewId = 6812d62294b968b803b01c65

### Créer une critique
POST http://localhost:3000/api/reviews
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "artworkId": "6632345a4fc2b400efcdd44e",
  "professionalId": "663234c1c012de0b0d159133",
  "comment": "Très belle réalisation, beaucoup de potentiel.",
  "rating": 4.5,
  "technicalReview": 4,
  "artisticMerit": 5,
  "marketPotential": 4
}

### Obtenir toutes les critiques
GET http://localhost:3000/api/reviews
x-api-key: {{apiKey}}

### Obtenir une critique par ID
GET http://localhost:3000/api/reviews/{{reviewId}}
x-api-key: {{apiKey}}

### Mettre à jour une critique
PUT http://localhost:3000/api/reviews/{{reviewId}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "rating": 5,
  "comment": "Mise à jour après réflexion, c'est un chef-d'œuvre."
}

### Supprimer une critique
DELETE http://localhost:3000/api/reviews/{{reviewId}}
x-api-key: {{apiKey}}
