@apiKey = $2ys6g542sb4fb6b42fb4db409df498fd41682b6df24b884f9852dthv143r4t52trfg4trs6gfcdg53g43g
@walletId = 6812d7adad0ede46a6668b8a

### Créer un portefeuille
POST http://localhost:3000/api/wallet
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "userId": "663234c1c012de0b0d159133",
  "walletAddress": "0xABCDEF1234567890",
  "balance": 50,
  "currency": "ETH",
  "transactions": ["6632ff63c012de0b0d159134"]
}

### Obtenir tous les wallet
GET http://localhost:3000/api/wallet
x-api-key: {{apiKey}}

### Obtenir un wallet par ID
GET http://localhost:3000/api/wallet/{{walletId}}
x-api-key: {{apiKey}}

### Mettre à jour un wallet
PUT http://localhost:3000/api/wallet/{{walletId}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "balance": 75,
  "currency": "USDT"
}

### Supprimer un wallet
DELETE http://localhost:3000/api/wallet/{{walletId}}
x-api-key: {{apiKey}}
